version: "3.9"
services:
  api:
    build: .
    container_name: app
    ports:
      - "8080:8080"
  DB:
    image: "mongo:latest"
    container_name: mongo


    volumes:
      - /DB/TestDb/mongodata:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped 
